//#define DEBUG 1

#define VERSION "1.2"

#define HAL_TRANSMITER_PPM
#define HAL_TRANSMITER_DIRS {1, -1, -1, 1, 1, 1, -1, 1};

#define HAL_BATTERY_PIN       A0
#define HAL_BATTERY_LOWCOEF   710
#define HAL_BATTERY_HIGHCOEF  878

#define HAL_CONSOLE_HOME_PIN  21
#define HAL_CONSOLE_UP_PIN    18
#define HAL_CONSOLE_DOWN_PIN  19

#define HAL_TRANSMITER_RUDDER_PIN    A1
#define HAL_TRANSMITER_RUDDER_TRIM1  3
#define HAL_TRANSMITER_RUDDER_TRIM2  2

#define HAL_TRANSMITER_THROTTLE_PIN    A2
#define HAL_TRANSMITER_THROTTLE_TRIM1  1
#define HAL_TRANSMITER_THROTTLE_TRIM2  0

#define HAL_TRANSMITER_AILERON_PIN    A4
#define HAL_TRANSMITER_AILERON_TRIM1  30
#define HAL_TRANSMITER_AILERON_TRIM2  31

#define HAL_TRANSMITER_ELEVATOR_PIN    A5
#define HAL_TRANSMITER_ELEVATOR_TRIM1  22
#define HAL_TRANSMITER_ELEVATOR_TRIM2  23

#define HAL_TRANSMITER_TRIGGER_AUX1A_PIN 18
#define HAL_TRANSMITER_TRIGGER_AUX1B_PIN 19

#define HAL_TRANSMITER_TRIGGER_AUX2_PIN  20

#define HAL_TRANSMITER_TRIGGER_AUX3A_PIN 13
#define HAL_TRANSMITER_TRIGGER_AUX3B_PIN 14

#define HAL_TRANSMITER_TRIGGER_AUX4_PIN 15

#define HAL_TRANSMITER_TRIGGER_KNOB1_PIN A3

#define HAL_SCHEDULER_QUANTUM_TIME  1000

#define HAL_STORAGE_MAX_MODELS  100

#define HAL_CONSOLE_WIDTH 20
#define HAL_CONSOLE_HEIGHT 4
