//#define DEBUG 1

#define VERSION "1.2"

#define HAL_TRANSMITER_PPM
#define HAL_TRANSMITER_DIRS {1, -1, -1, 1, 1, 1, 1, 1};

#define HAL_BATTERY_PIN       A7
#define HAL_BATTERY_LOWCOEF   420
#define HAL_BATTERY_HIGHCOEF  500

#define HAL_CONSOLE_HOME_PIN  0
#define HAL_CONSOLE_DOWN_PIN  2
#define HAL_CONSOLE_UP_PIN    3

#define HAL_TRANSMITER_AILERON_PIN    A0
#define HAL_TRANSMITER_AILERON_TRIM1  19
#define HAL_TRANSMITER_AILERON_TRIM2  18

#define HAL_TRANSMITER_ELEVATOR_PIN    A1
#define HAL_TRANSMITER_ELEVATOR_TRIM1  14
#define HAL_TRANSMITER_ELEVATOR_TRIM2  15

#define HAL_TRANSMITER_RUDDER_PIN    A3
#define HAL_TRANSMITER_RUDDER_TRIM1  20
#define HAL_TRANSMITER_RUDDER_TRIM2  21

#define HAL_TRANSMITER_THROTTLE_PIN    A2
#define HAL_TRANSMITER_THROTTLE_TRIM1  22
#define HAL_TRANSMITER_THROTTLE_TRIM2  23

#define HAL_TRANSMITER_TRIGGER_TOP_PIN  1

#define HAL_TRANSMITER_TRIGGER_RIGHT1_PIN 3
#define HAL_TRANSMITER_TRIGGER_RIGHT2_PIN 2

#define HAL_TRANSMITER_TRIGGER_LEFT1_PIN 11
#define HAL_TRANSMITER_TRIGGER_LEFT2_PIN 10

#define HAL_SCHEDULER_QUANTUM_TIME  1

#define HAL_STORAGE_MAX_MODELS  100
